-- ============================================
-- Query 1: Customer Purchase History
-- Business Question:
-- Generate a detailed report showing each customer’s name,
-- total number of orders, and total amount spent.
-- Expected to return customers with 2+ orders and >5000 spent
--
-- Expected Output Columns:
-- customer_id, customer_name, total_orders, total_spent
-- ============================================

SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, customer_name
HAVING COUNT(o.order_id) >= 2
   AND SUM(o.total_amount) > 5000;


-- ============================================
-- Query 2: Product Sales Analysis
-- Business Question:
-- Analyze total revenue generated by each product category.
-- Expected to return categories with revenue > 10000
--
-- Expected Output Columns:
-- category, total_revenue
-- ============================================

SELECT
    p.category,
    SUM(oi.subtotal) AS total_revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.category
HAVING SUM(oi.subtotal) > 10000;


-- ============================================
-- Query 3: Monthly Sales Trend
-- Business Question:
-- Show monthly revenue trends along with cumulative revenue.
--
-- Expected Output Columns:
-- month, monthly_revenue, cumulative_revenue
-- ============================================

SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(o.total_amount) AS monthly_revenue,
    SUM(SUM(o.total_amount)) OVER (
        ORDER BY DATE_FORMAT(o.order_date, '%Y-%m')
    ) AS cumulative_revenue
FROM orders o
GROUP BY month
ORDER BY month;
